apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-k8s-dep
spec:
  selector:
    matchLabels:
      app: user
  replicas: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:2.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---

apiVersion: v1
kind: Service
metadata:
  name: user-k8s-svc
spec:
  selector:
    app: user
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort