apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-k8s-dep
spec:
  selector:
    matchLabels:
      app: user
  replicas: 2
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:1.5
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: user
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
---

apiVersion: v1
kind: Service
metadata:
  name: user-k8s-svc
spec:
  selector:
    app: user
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort